version: '3'
services:
  mysqldb-service: ##MySQL DB which runs on port 3306
    image: 'mysql:5.7'
    environment:
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3307:3306"
  apiservice-docker-container: ##Spring Boot REST API which runs on port 8080.
    image: apiservice-docker-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysqldb-service